-- ==========================================================
-- ФИНАЛЬНЫЙ СКРИПТ СТРУКТУРЫ БД (v9.0)
-- Gym Management System
-- 
-- ВАЖНО: Выполнять внутри уже созданной базы gym_db
-- Пользователь gym_app_user должен быть создан отдельно
-- ==========================================================

-- Настройки сессии
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- ==========================================================
-- 1. ТАБЛИЦА СОТРУДНИКОВ (тренеры, администраторы зала)
-- ==========================================================
CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    phone VARCHAR(20) UNIQUE,
    position VARCHAR(30) NOT NULL DEFAULT 'administrator',
    is_active BOOLEAN DEFAULT true,
    
    CONSTRAINT chk_employee_position CHECK (
        position IN ('administrator', 'trainer', 'manager', 'director', 'cleaner')
    )
);

-- ==========================================================
-- 2. ТАБЛИЦА ПОЛЬЗОВАТЕЛЕЙ СИСТЕМЫ (для авторизации)
-- ==========================================================
CREATE TABLE system_users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INT UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
    login VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'operator',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_system_role CHECK (
        role IN ('admin', 'operator')
    )
);

-- ==========================================================
-- 3. ТАБЛИЦА КЛИЕНТОВ
-- ==========================================================
CREATE TABLE clients (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(150) UNIQUE,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    is_deleted BOOLEAN DEFAULT false,
    
    CONSTRAINT chk_client_status CHECK (
        status IN ('active', 'inactive', 'blacklisted')
    )
);

-- ==========================================================
-- 4. ТАБЛИЦА АБОНЕМЕНТОВ
-- ==========================================================
CREATE TABLE memberships (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    type VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_visits INT NOT NULL DEFAULT 0,
    used_visits INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    
    CONSTRAINT chk_membership_type CHECK (
        type IN ('single', 'month', 'year')
    ),
    CONSTRAINT chk_membership_status CHECK (
        status IN ('active', 'completed', 'expired', 'cancelled')
    ),
    CONSTRAINT chk_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_visits_positive CHECK (total_visits >= 0 AND used_visits >= 0),
    CONSTRAINT chk_used_vs_total CHECK (total_visits = 0 OR used_visits <= total_visits)
);

-- ==========================================================
-- 5. ТАБЛИЦА ПОСЕЩЕНИЙ
-- ==========================================================
CREATE TABLE visits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id INT NOT NULL REFERENCES memberships(id) ON DELETE RESTRICT,
    trainer_id INT REFERENCES employees(id) ON DELETE SET NULL,
    processed_by_user_id INT REFERENCES system_users(id) ON DELETE SET NULL,
    visit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 6. ИНДЕКСЫ ДЛЯ ПРОИЗВОДИТЕЛЬНОСТИ
-- ==========================================================

-- По абонементам (частые запросы по клиенту и статусу)
CREATE INDEX idx_memberships_client_id ON memberships(client_id);
CREATE INDEX idx_memberships_status ON memberships(status);

-- По посещениям (частые запросы по абонементу и времени)
CREATE INDEX idx_visits_membership_id ON visits(membership_id);
CREATE INDEX idx_visits_visit_time ON visits(visit_time);

-- По клиентам (фильтрация по статусу и поиск по телефону)
CREATE INDEX idx_clients_status ON clients(status);
CREATE INDEX idx_clients_phone ON clients(phone);

-- По сотрудникам (фильтрация по должности)
CREATE INDEX idx_employees_position ON employees(position);

-- По пользователям (поиск по логину при авторизации)
CREATE INDEX idx_system_users_login ON system_users(login);

-- ==========================================================
-- 7. ТРИГГЕР: ЗАЩИТА ИСТОРИИ ПОСЕЩЕНИЙ
-- Запрещает изменять membership_id и visit_time в существующих записях
-- ==========================================================
CREATE OR REPLACE FUNCTION protect_visit_history()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.membership_id IS DISTINCT FROM NEW.membership_id OR
       OLD.visit_time IS DISTINCT FROM NEW.visit_time THEN
        RAISE EXCEPTION 'Historical visit data cannot be modified';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_protect_visit_history
BEFORE UPDATE ON visits
FOR EACH ROW
EXECUTE FUNCTION protect_visit_history();

-- ==========================================================
-- 8. ПРАВА ДОСТУПА ДЛЯ ПОЛЬЗОВАТЕЛЯ ПРИЛОЖЕНИЯ
-- ==========================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gym_app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gym_app_user;

-- Права по умолчанию для будущих таблиц
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gym_app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT USAGE, SELECT ON SEQUENCES TO gym_app_user;