-- ==========================================================
-- ФИНАЛЬНЫЙ СКРИПТ МОДУЛЯ 0 (v8.0)
-- Выполнять внутри базы gym_db
-- ==========================================================
\echo 'RUN'
-- 1. Перечисления (ENUM)
CREATE TYPE client_status_enum AS ENUM ('active', 'inactive', 'blacklisted');
CREATE TYPE membership_type_enum AS ENUM ('single', 'month', 'year');
CREATE TYPE membership_status_enum AS ENUM ('active', 'completed', 'expired', 'cancelled');
CREATE TYPE system_role_enum AS ENUM ('admin', 'operator');
CREATE TYPE employee_position_enum AS ENUM ('administrator', 'trainer', 'manager', 'director', 'cleaner');

-- 2. Таблица сотрудников
CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    phone VARCHAR(20) UNIQUE,
    position employee_position_enum NOT NULL DEFAULT 'administrator',
    is_active BOOLEAN DEFAULT true
);

-- 3. Таблица пользователей системы
CREATE TABLE system_users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INT UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
    login VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role system_role_enum DEFAULT 'operator',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Таблица клиентов
CREATE TABLE clients (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(150) UNIQUE,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status client_status_enum DEFAULT 'active',
    is_deleted BOOLEAN DEFAULT false
);

-- 5. Таблица абонементов
CREATE TABLE memberships (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    type membership_type_enum NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_visits INT NOT NULL DEFAULT 0,
    used_visits INT NOT NULL DEFAULT 0,
    status membership_status_enum DEFAULT 'active',
    CONSTRAINT chk_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_visits_positive CHECK (total_visits >= 0 AND used_visits >= 0),
    CONSTRAINT chk_used_vs_total CHECK (total_visits = 0 OR used_visits <= total_visits)
);

-- 6. Таблица посещений
CREATE TABLE visits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id INT NOT NULL REFERENCES memberships(id) ON DELETE RESTRICT,
    trainer_id INT REFERENCES employees(id) ON DELETE SET NULL,
    processed_by_user_id INT REFERENCES system_users(id) ON DELETE SET NULL,
    visit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. Индексы
CREATE INDEX idx_memberships_client_id ON memberships(client_id);
CREATE INDEX idx_memberships_status ON memberships(status);
CREATE INDEX idx_visits_membership_id ON visits(membership_id);
CREATE INDEX idx_visits_visit_time ON visits(visit_time);

-- 8. Триггер: Защита истории посещений
CREATE OR REPLACE FUNCTION protect_visit_history()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.membership_id IS DISTINCT FROM NEW.membership_id OR
       OLD.visit_time IS DISTINCT FROM NEW.visit_time THEN
        RAISE EXCEPTION 'Historical visit data cannot be modified';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_protect_visit_history
BEFORE UPDATE ON visits
FOR EACH ROW
EXECUTE FUNCTION protect_visit_history();

-- 9. Права
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gym_app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gym_app_user;
